<?php

global $DJ4E_DJANGO_VERISION, $DJ4E_DJANGO_VERISION_SHORT;

$DJ4E_DJANGO_VERISION = '5.2';
$DJ4E_DJANGO_VERISION_SHORT = '52';
$DJ4E_DJANGO_VENV_PROMPT = '.ve52';
$DJ4E_DJANGO_VENV_PYTHON = 'Python 3.10.5';
$DJ4E_DJANGO_VENV_DJANGO = '5.2';

