<?php
$ad_titles = array(
"For Sale: Vintage Camera Collection",
"Seeking Roommate for Downtown Apartment",
"Job Opportunity: Marketing Assistant",
"Renting: Cozy Studio in the Heart of the City",
"Lost: Family Heirloom Bracelet",
"Garage Sale: Furniture, Electronics, and More!",
"Pet Sitting Services Available",
"Wanted: Used Car in Good Condition",
"Tutoring Services: Math, Science, and English",
"Hiring: Experienced Chef for New Restaurant",
"Seeking Babysitter for Weekends",
"Freelance Graphic Designer Available for Projects",
"For Sale: Antique Dining Table and Chairs",
"Yoga Classes Offered - All Levels Welcome!",
"Lost Cat: Grey Tabby, Answers to Luna",
"Job Opportunity: Administrative Assistant",
"Renting: Spacious 2-Bedroom Apartment",
"Guitar Lessons Available: Beginner to Advanced",
"Selling: Brand New iPhone 12 (Unlocked)",
"Need a Handyman? Call for Affordable Repairs!",
"Wanted: Roommate for Shared House",
"Experienced Cleaner Available for Housekeeping",
"Pet Adoption: Rescue Puppies Looking for Homes",
"Hiring: Part-Time Retail Associates",
"Seeking Dog Walker for Afternoons",
"Freelance Writer Available for Content Creation",
"For Sale: Vintage Vinyl Record Collection",
"Fitness Training Sessions - Get in Shape Today!",
"Lost Dog: Golden Retriever, Answers to Max",
"Job Opportunity: Customer Service Representative",
"Renting: Furnished Apartment Near Public Transit",
"Piano Lessons Available: Classical and Jazz Styles",
"Selling: Used MacBook Pro in Excellent Condition",
"Need Plumbing Repairs? Call for Quick Service!",
"Wanted: Bicycle for Commuting to Work",
"Babysitting Services Available Evenings and Weekends",
"Graphic Design Services: Logos, Flyers, and More",
"For Sale: Designer Handbags and Accessories",
"Meditation Classes Offered - Find Your Inner Peace",
"Missing: Silver Bracelet with Heart Charm",
"Job Opportunity: Sales Associate for Retail Store",
"Renting: Modern Loft with City Views",
"Spanish Tutor Available for Private Lessons",
"Selling: Antique China Cabinet",
"Handyman Services: Repairs, Installations, and More",
"Seeking Travel Buddy for Cross-Country Road Trip",
"Pet Grooming Services: Pamper Your Furry Friend",
"Hiring: Barista for Busy Café",
"Dog Training Sessions Available - Obedience and Behavior",
"Freelance Photographer for Events and Portraits",
"For Sale: Vintage Clothing Collection",
"Yoga Retreat Weekend - Join Us for Relaxation",
"Lost: Diamond Engagement Ring",
"Job Opportunity: Receptionist for Medical Office",
"Renting: Charming Cottage in Quiet Neighborhood",
"Guitar Repair Services: Restringing, Setup, and More",
"Selling: Home Theater System with Surround Sound",
"Lawn Care Services: Mowing, Edging, and Maintenance",
"Wanted: Used Motorcycle in Good Running Condition",
"Childcare Services: Experienced and Reliable",
"Graphic Design Services: Business Cards, Brochures, and More",
"For Sale: Rare Comic Book Collection",
"Meditation Workshop - Learn Techniques for Stress Relief",
"Missing Cat: Black and White, Named Whiskers",
"Job Opportunity: IT Support Technician",
"Renting: Luxury Condo with Amenities",
"French Tutor Available for Language Lessons",
"Selling: Vintage Rolex Watch",
"House Painting Services: Interior and Exterior",
"Seeking Running Partner for Early Morning Runs",
"Pet Boarding Services Available - Safe and Loving Environment",
"Hiring: Waitstaff for Upscale Restaurant",
"Photography Lessons: Learn to Capture Memories",
"For Sale: Antique Persian Rug",
"Yoga Teacher Training Course - Deepen Your Practice",
"Lost: Wedding Ring Set",
"Job Opportunity: Entry-Level Accountant",
"Renting: Renovated Townhouse in Historic District",
"Drum Lessons Available: Beginner to Advanced",
"Selling: Collectible Star Wars Memorabilia",
"Landscaping Services: Design, Installation, and Maintenance",
"Wanted: Used RV for Family Camping Trips",
"Dog Walking Services: Regular Exercise for Your Pup",
"Hiring: Receptionist for Law Firm",
"Art Classes Offered: Painting, Drawing, and Sculpture",
"For Sale: Vintage Typewriter Collection",
"Mindfulness Retreat - Find Clarity and Peace",
"Missing Dog: Brown Labrador, Named Buddy",
"Job Opportunity: Graphic Designer for Digital Agency",
"Renting: Spacious Loft in Trendy Neighborhood",
"Spanish Lessons Available: Beginner to Advanced Levels",
"Selling: Antique Oak Dining Set",
"Plumbing Services: Repairs, Installations, and Maintenance",
"Wanted: Used Kayak for Summer Adventures",
"Babysitter Available for Weeknights",
"Freelance Web Developer for Website Projects",
"For Sale: Rare Stamp Collection",
"Fitness Classes Offered: HIIT, Yoga, and Pilates",
"Lost: Prescription Glasses with Tortoiseshell Frames",
"Job Opportunity: Freelance Writer for Online Publication",
);

