<?php

$quotes = array(
array("Author","Quote"),
array("Yogi Berra","You can observe a lot just by watching."),
array("Abraham Lincoln","A house divided against itself cannot stand."),
array("Byron Pulsifer","Fate is in your hands and no one elses"),
array("Lao Tzu","Be the chief but never the lord."),
array("Carl Sandburg","Nothing happens unless first we dream."),
array("Aristotle","Well begun is half done."),
array("Yogi Berra","Life is a learning experience, only if you learn."),
array("Margaret Sangster","Self-complacency is fatal to progress."),
array("Buddha","Peace comes from within. Do not seek it without."),
array("Byron Pulsifer","What you give is what you get."),
array("Iris Murdoch","We can only learn to love by loving."),
array("Karen Clark","Life is change. Growth is optional. Choose wisely."),
array("Wayne Dyer","You'll see it when you believe it."),
array("","Today is the tomorrow we worried about yesterday."),
array("","It's easier to see the mistakes on someone else's paper."),
array("","Every man dies. Not every man really lives."),
array("Lao Tzu","To lead people walk behind them."),
array("William Shakespeare","Having nothing, nothing can he lose."),
array("Henry J. Kaiser","Trouble is only opportunity in work clothes."),
array("Publilius Syrus","A rolling stone gathers no moss."),
array("Napoleon Hill","Ideas are the beginning points of all fortunes."),
array("Donald Trump","Everything in life is luck."),
array("Lao Tzu","Doing nothing is better than being busy doing nothing."),
array("Benjamin Spock","Trust yourself. You know more than you think you do."),
array("Confucius","Study the past, if you would divine the future."),
array("","The day is already blessed, find peace within it."),
array("Sigmund Freud","From error to error one discovers the entire truth."),
array("Benjamin Franklin","Well done is better than well said."),
array("Ella Williams","Bite off more than you can chew, then chew it."),
array("Buddha","Work out your own salvation. Do not depend on others."),
array("Benjamin Franklin","One today is worth two tomorrows."),
array("Christopher Reeve","Once you choose hope, anythings possible."),
array("Albert Einstein","God always takes the simplest way."),
array("Charles Kettering","One fails forward toward success."),
array("","From small beginnings come great things."),
array("Chinese proverb","Learning is a treasure that will follow its owner everywhere"),
array("Socrates","Be as you wish to seem."),
array("V. Naipaul","The world is always in movement."),
array("John Wooden","Never mistake activity for achievement."),
array("Haddon Robinson","What worries you masters you."),
array("Pearl Buck","One faces the future with ones past."),
array("Brian Tracy","Goals are the fuel in the furnace of achievement."),
array("Leonardo da Vinci","Who sows virtue reaps honour."),
array("Dalai Lama","Be kind whenever possible. It is always possible."),
array("Chinese proverb","Talk doesn't cook rice."),
array("Buddha","He is able who thinks he is able."),
array("Larry Elder","A goal without a plan is just a wish."),
array("Michael Korda","To succeed, we must first believe that we can."),
array("Albert Einstein","Learn from yesterday, live for today, hope for tomorrow."),
array("James Lowell","A weed is no more than a flower in disguise."),
array("Yoda","Do, or do not. There is no try."),
array("Harriet Beecher Stowe","All serious daring starts from within."),
array("Byron Pulsifer","The best teacher is experience learned from failures."),
array("Murray Gell-Mann","Think how hard physics would be if particles could think."),
array("John Lennon","Love is the flower you've got to let grow."),
array("Napoleon Hill","Don't wait. The time will never be just right."),
array("Pericles","Time is the wisest counsellor of all."),
array("Napoleon Hill","You give before you get."),
array("Socrates","Wisdom begins in wonder."),
array("Baltasar Gracian","Without courage, wisdom bears no fruit."),
array("Aristotle","Change in all things is sweet."),
array("African proverb","When deeds speak, words are nothing."),
array("Albert Einstein","I never think of the future. It comes soon enough."),
array("Ralph Emerson","Skill to do comes of doing."),
array("Sophocles","Wisdom is the supreme part of happiness."),
array("Maya Angelou","I believe that every person is born with talent."),
array("Abraham Lincoln","Important principles may, and must, be inflexible."),
array("Richard Evans","The undertaking of a new action brings new strength."),
array("Ralph Emerson","The years teach much which the days never know."),
array("Ralph Emerson","Our distrust is very expensive."),
array("Bodhidharma","All know the way; few actually walk it."),
array("Johann Wolfgang von Goethe","Great talent finds happiness in execution."),
array("Michelangelo","Faith in oneself is the best and safest course."),
array("Leo Tolstoy","The two most powerful warriors are patience and time."),
array("Lao Tzu","Anticipate the difficult by managing the easy."),
array("Buddha","Those who are free of resentful thoughts surely find peace."),
array("Sophocles","A short saying often contains much wisdom."),
array("","It takes both sunshine and rain to make a rainbow."),
array("","A beautiful thing is never perfect."),
array("Princess Diana","Only do what your heart tells you."),
array("John Pierrakos","Life is movement-we breathe, we eat, we walk, we move!"),
array("Eleanor Roosevelt","No one can make you feel inferior without your consent."),
array("Richard Bach","Argue for your limitations, and sure enough theyre yours."),
array("Seneca","Luck is what happens when preparation meets opportunity."),
array("Napoleon Bonaparte","Victory belongs to the most persevering."),
array("William Shakespeare","Love all, trust a few, do wrong to none."),
array("Richard Bach","In order to win, you must expect to win."),
array("Napoleon Hill","A goal is a dream with a deadline."),
array("Napoleon Hill","You can do it if you believe you can!"),
array("Bo Jackson","Set your goals high, and don't stop till you get there."),
array("","Every new day is another chance to change your life."),
array("Thich Nhat Hanh","Smile, breathe, and go slowly."),
array("Liberace","Nobody will believe in you unless you believe in yourself."),
array("William Arthur Ward","Do more than dream: work."),
array("Seneca","No man was ever wise by chance."),
array("","Some pursue happiness, others create it."),
array("William Shakespeare","He that is giddy thinks the world turns round."),
array("Ellen Gilchrist","Don't ruin the present with the ruined past."),
array("Albert Schweitzer","Do something wonderful, people may imitate it."),
array("","We do what we do because we believe."),
array("Eleanor Roosevelt","Do one thing every day that scares you."),
array("Byron Pulsifer","If you cannot be silent be brilliant and thoughtful."),
array("Carl Jung","Who looks outside, dreams; who looks inside, awakes."),
array("Buddha","What we think, we become."),
array("Lord Herbert","The shortest answer is doing."),
array("Leonardo da Vinci","All our knowledge has its origins in our perceptions."),
array("","The harder you fall, the higher you bounce."),
array("Anne Wilson Schaef","Trusting our intuition often saves us from disaster."),
array("Sojourner Truth","Truth is powerful and it prevails."),
array("Elizabeth Browning","Light tomorrow with today!"),
array("German proverb","Silence is a fence around wisdom."),
array("Madame de Stael","Society develops wit, but its contemplation alone forms genius."),
array("Richard Bach","The simplest things are often the truest."),
array("","Everyone smiles in the same language."),
array("Bernadette Devlin","Yesterday I dared to struggle. Today I dare to win."),
array("Napoleon Hill","No alibi will save you from accepting the responsibility."),
array("Walt Disney","If you can dream it, you can do it."),
array("Buddha","It is better to travel well than to arrive."),
array("Anais Nin","Life shrinks or expands in proportion to one's courage."),
array("Sun Tzu","You have to believe in yourself."),
array("Wayne Dyer","Our intention creates our reality."),
array("Confucius","Silence is a true friend who never betrays."),
array("Johann Wolfgang von Goethe","Character develops itself in the stream of life."),
array("American proverb","From little acorns mighty oaks do grow."),
array("Jon Kabat-Zinn","You can't stop the waves, but you can learn to surf."),
array("Gustave Flaubert","Reality does not conform to the ideal, but confirms it."),
array("William Shakespeare","Speak low, if you speak love."),
array("John Lennon","Reality leaves a lot to the imagination."),
array("Seneca","The greatest remedy for anger is delay."),
array("Pearl Buck","Growth itself contains the germ of happiness."),
array("","You can do what's reasonable or you can decide what's possible."),
array("Leonardo da Vinci","Nothing strengthens authority so much as silence."),
array("Confucius","Wherever you go, go with all your heart."),
array("Albert Einstein","The only real valuable thing is intuition."),
array("Ralph Emerson","Good luck is another name for tenacity of purpose."),
array("Sylvia Voirol","Rainbows apologize for angry skies."),
array("","Friendship isn't a big thing. It's a million little things."),
array("Theophrastus","Time is the most valuable thing a man can spend."),
array("Tony Robbins","Whatever happens, take responsibility."),
array("Oscar Wilde","Experience is simply the name we give our mistakes."),
array("Wayne Dyer","I think and that is all that I am."),
array("","A good plan today is better than a perfect plan tomorrow."),
array("Gloria Steinem","If the shoe doesn't fit, must we change the foot?"),
array("Marcus Aurelius","Each day provides its own gifts."),
array("Publilius Syrus","While we stop to think, we often miss our opportunity."),
array("Bernard Shaw","Life isn't about finding yourself. Life is about creating yourself."),
array("Richard Bach","To bring anything into your life, imagine that it's already there."),
array("German proverb","Begin to weave and God will give you the thread."),
array("Confucius","The more you know yourself, the more you forgive yourself."),
array("","Someone remembers, someone cares; your name is whispered in someone's prayers."),
array("Mary Bethune","Without faith, nothing is possible. With it, nothing is impossible."),
array("Albert Einstein","Once we accept our limits, we go beyond them."),
array("","Don't be pushed by your problems; be led by your dreams."),
array("Brian Tracy","Whatever we expect with confidence becomes our own self-fulfilling prophecy."),
array("Pablo Picasso","Everything you can imagine is real."),
array("Usman Asif","Fear is a darkroom where negatives develop."),
array("Napoleon Bonaparte","The truest wisdom is a resolute determination."),
array("Victor Hugo","Life is the flower for which love is the honey."),
array("Epictetus","Freedom is the right to live as we wish."),
array("","Change your thoughts, change your life!"),
array("Robert Heller","Never ignore a gut feeling, but never believe that it's enough."),
array("Marcus Aurelius","Loss is nothing else but change,and change is Natures delight."),
array("Byron Pulsifer","Someone is special only if you tell them."),
array("","Today is the tomorrow you worried about yesterday."),
array("Thich Nhat Hanh","There is no way to happiness, happiness is the way."),
array("","The day always looks brighter from behind a smile."),
array("","A stumble may prevent a fall."),
array("Lao Tzu","He who talks more is sooner exhausted."),
array("Lao Tzu","He who is contented is rich."),
array("Plutarch","What we achieve inwardly will change outer reality."),
array("Ralph Waldo Emerson","Our strength grows out of our weaknesses."),
array("Mahatma Gandhi","We must become the change we want to see."),
array("Napoleon Hill","Happiness is found in doing, not merely possessing."),
array("","Put your future in good hands : your own."),
array("Wit","We choose our destiny in the way we treat others."),
array("Voltaire","No snowflake in an avalanche ever feels responsible."),
array("Virgil","Fortune favours the brave."),
array("Joseph Stalin","I believe in one thing only, the power of human will."),
array("Robert Frost","The best way out is always through."),
array("Seneca","The mind unlearns with difficulty what it has long learned."),
array("Abraham Lincoln","I destroy my enemies when I make them my friends."),
array("Thomas Fuller","No garden is without its weeds."),
array("Elbert Hubbard","There is no failure except in no longer trying."),
array("Turkish proverb","Kind words will unlock an iron door."),
array("Hugh Miller","Problems are only opportunities with thorns on them."),
array("A. Powell Davies","Life is just a chance to grow a soul."),
array("John Dryden","Fortune befriends the bold."),
array("Friedrich von Schiller","Keep true to the dreams of thy youth."),
array("Mike Ditka","You're never a loser until you quit trying."),
array("Immanuel Kant","Science is organized knowledge. Wisdom is organized life."),
array("Johann Wolfgang von Goethe","Knowing is not enough; we must apply!"),
array("Richard Bach","Strong beliefs win strong men, and then make them stronger."),
array("Albert Camus","Autumn is a second spring when every leaf is a flower."),
array("Toni Morrison","If you surrender to the wind, you can ride it."),
array("Helen Keller","Keep yourself to the sunshine and you cannot see the shadow."),
array("Paulo Coelho","Write your plans in pencil and give God the eraser."),
array("Pablo Picasso","Inspiration exists, but it has to find us working."),
array("Jonathan Kozol","Pick battles big enough to matter, small enough to win."),
array("Janis Joplin","Don't compromise yourself. You are all you've got."),
array("Sophocles","A short saying oft contains much wisdom."),
array("Epictetus","Difficulties are things that show a person what they are."),
array("Honore de Balzac","When you doubt your power, you give power to your doubt."),
array("Ovid","The cause is hidden. The effect is visible to all."),
array("Francis Bacon","A prudent question is one half of wisdom."),
array("Tony Robbins","The path to success is to take massive, determined action."),
array("Manuel Puig","I allow my intuition to lead my path."),
array("William R. Inge","Nature takes away any faculty that is not used."),
array("Epictetus","If you wish to be a writer, write."),
array("Wayne Dyer","There is no way to prosperity, prosperity is the way."),
array("Jim Rohn","Either you run the day or the day runs you."),
array("Publilius Syrus","Better be ignorant of a matter than half know it."),
array("Oprah Winfrey","Follow your instincts. That is where true wisdom manifests itself."),
array("Benjamin Franklin","There never was a good knife made of bad steel."),
array("Anatole France","To accomplish great things, we must dream as well as act."),
array("Saint Augustine","Patience is the companion of wisdom."),
array("Buddha","The mind is everything. What you think you become."),
array("Voltaire","To enjoy life, we must touch much of it lightly."),
array("Maya Lin","To fly, we have to have resistance."),
array("","What you see depends on what you're looking for."),
array("Blaise Pascal","The heart has its reasons which reason knows not of."),
array("William Shakespeare","Be great in act, as you have been in thought."),
array("Napoleon Bonaparte","Imagination rules the world."),
array("Blaise Pascal","Kind words do not cost much. Yet they accomplish much."),
array("Michelangelo","There is no greater harm than that of time wasted."),
array("Jonas Salk","Intuition will tell the thinking mind where to look next."),
array("","Worry gives a small thing a big shadow."),
array("Napoleon Hill","Fears are nothing more than a state of mind."),
array("Lao Tzu","The journey of a thousand miles begins with one step."),
array("Luisa Sigea","Blaze with the fire that is never extinguished."),
array("Dr. Seuss","Don't cry because it's over. Smile because it happened."),
array("Jason Fried","No is easier to do. Yes is easier to say."),
array("Confucius","To be wrong is nothing unless you continue to remember it."),
array("Babe Ruth","Yesterdays home runs don't win today's games."),
array("Carlyle","Silence is deep as Eternity, Speech is shallow as Time."),
array("Leo F. Buscaglia","Don't smother each other. No one can grow in the shade."),
array("Lao Tzu","An ant on the move does more than a dozing ox"),
array("Indira Gandhi","You can't shake hands with a clenched fist."),
array("Plato","A good decision is based on knowledge and not on numbers."),
array("Confucius","The cautious seldom err."),
array("Frederick Douglass","If there is no struggle, there is no progress."),
array("Willa Cather","Where there is great love, there are always miracles."),
array("John Lennon","Time you enjoy wasting, was not wasted."),
array("Richard Bach","Every problem has a gift for you in its hands."),
array("Jean de la Fontaine","Sadness flies away on the wings of time."),
array("Publilius Syrus","I have often regretted my speech, never my silence."),
array("Thomas Jefferson","Never put off till tomorrow what you can do today."),
array("Thomas Dewar","Minds are like parachutes. They only function when open."),
array("George Patton","If a man does his best, what else is there?"),
array("Benjamin Disraeli","The secret of success is constancy to purpose."),
array("Ralph Emerson","Life is a progress, and not a station."),
array("Horace Friess","All seasons are beautiful for the person who carries happiness within."),
array("Elbert Hubbard","To avoid criticism, do nothing, say nothing, be nothing."),
array("Ovid","All things change; nothing perishes."),
array("Haynes Bayly","Absence makes the heart grow fonder."),
array("Lauren Bacall","Imagination is the highest kite one can fly."),
array("Edward Gibbon","The winds and waves are always on the side of the ablest navigators."),
array("","To get something you never had, you have to do something you never did."),
array("","Be thankful when you don't know something for it gives you the opportunity to learn."),
array("Og Mandino","Each misfortune you encounter will carry in it the seed of tomorrows good luck."),
array("Lewis B. Smedes","To forgive is to set a prisoner free and realize that prisoner was you."),
array("Nikos Kazantzakis","By believing passionately in something that does not yet exist, we create it."),
array("","Letting go isn't the end of the world; it's the beginning of a new life."),
array("John Eliot","All the great performers I have worked with are fuelled by a personal dream."),
array("Marie Curie","I never see what has been done; I only see what remains to be done."),
array("Seneca","Begin at once to live and count each separate day as a separate life."),
array("Lawrence Peter","If you don't know where you are going, you will probably end up somewhere else."),
array("Hannah More","It is not so important to know everything as to appreciate what we learn."),
array("John Berry","The bird of paradise alights only upon the hand that does not grasp."),
array("William Yeats","Think as a wise man but communicate in the language of the people."),
array("Epictetus","Practice yourself, for heavens sake in little things, and then proceed to greater."),
array("Seneca","If one does not know to which port is sailing, no wind is favorable."),
array("","Our greatest glory is not in never failing but rising everytime we fall."),
array("","Being right is highly overrated. Even a stopped clock is right twice a day."),
array("Ken S. Keyes","To be upset over what you don't have is to waste what you do have."),
array("Thomas Edison","If we did the things we are capable of, we would astound ourselves."),
array("Marie Curie","Nothing in life is to be feared. It is only to be understood."),
array("Tony Robbins","Successful people ask better questions, and as a result, they get better answers."),
array("","Love is not blind; it simply enables one to see things others fail to see."),
array("Anne Schaef","Life is a process. We are a process. The universe is a process."),
array("Eleanor Roosevelt","I think somehow we learn who we really are and then live with that decision."),
array("Kahlil Gibran","A little knowledge that acts is worth infinitely more than much knowledge that is idle."),
array("","If you get up one more time than you fall, you will make it through."),
array("Flora Whittemore","The doors we open and close each day decide the lives we live."),
array("H. W. Arnold","The worst bankrupt in the world is the person who has lost his enthusiasm."),
array("Buddha","Happiness comes when your work and words are of benefit to yourself and others."),
array("","Don't focus on making the right decision, focus on making the decision the right one."),
array("Wayne Dyer","Everything is perfect in the universe, even your desire to improve it."),
array("Buddha","Just as a candle cannot burn without fire, men cannot live without a spiritual life."),
array("Mark Twain","A thing long expected takes the form of the unexpected when at last it comes."),
array("Benjamin Disraeli","Action may not always bring happiness; but there is no happiness without action."),
array("Oprah Winfrey","I don't believe in failure. It is not failure if you enjoyed the process."),
array("Confucius","What you do not want done to yourself, do not do to others."),
array("Winston Churchill","Short words are best and the old words when short are best of all."),
array("Buddha","If you light a lamp for somebody, it will also brighten your path."),
array("Lin-yutang","I have done my best: that is about all the philosophy of living one needs."),
array("Byron Pulsifer","Give thanks for the rain of life that propels us to reach new horizons."),
array("","Love is just a word until someone comes along and gives it meaning."),
array("","We all have problems. The way we solve them is what makes us different."),
array("Dave Weinbaum","The secret to a rich life is to have more beginnings than endings."),
array("Ralph Waldo Emerson","It is only when the mind and character slumber that the dress can be seen."),
array("Maya Angelou","If you don't like something, change it. If you can't change it, change your attitude."),
array("Confucius","Reviewing what you have learned and learning anew, you are fit to be a teacher."),
);


